<a href="https://colab.research.google.com/github/glcn35/PANDAS/blob/main/Assignment_1_Student_(D1178_G%C3%9CLCAN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [ ]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [ ]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [ ]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [ ]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [ ]:
a=np.ones((4,4),dtype=int)
b=np.where(1,7,a)
b

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
c=np.where(1,7,a[2,2])
c

array(7)

In [ ]:
#a.reshape((2,8))

#### 6. Create same array above with full method

In [ ]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [ ]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [ ]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [ ]:
np.linspace(0,24,25).reshape(5,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

#### 10. Create 5 random number with numpy

In [ ]:
np.random.rand(5)

array([0.03904011, 0.32599961, 0.48997738, 0.28531609, 0.02620522])

#### 11. Create random normal distributed 5x5 array

In [ ]:
np.random.rand(5,5)

array([[0.64793332, 0.72603333, 0.64195564, 0.04987598, 0.34556392],
       [0.81622743, 0.03016139, 0.2134552 , 0.03433783, 0.91600433],
       [0.21835529, 0.59414968, 0.50768707, 0.70544265, 0.55845407],
       [0.57444579, 0.60264511, 0.96371036, 0.13582568, 0.07213311],
       [0.48255955, 0.89455651, 0.56992147, 0.34314011, 0.17222202]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [ ]:
np.random.randint(20,50,size=(3,4))

array([[30, 40, 28, 45],
       [42, 45, 34, 31],
       [22, 42, 44, 48]])

#### 13. Reshape the array below with shape 6x8

In [ ]:
ranarr=[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]

In [ ]:
ranarr= np.array(ranarr)
ranarr

array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [ ]:
ranarr.reshape(6,8)
#np.array(ranarr).reshape(6,8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [ ]:
#reshape with -1
ranarr.reshape(-1,12)  #(12,-1) de çalışır


array([[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8],
       [44,  2, 46, 27, 11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17, 20, 42, 23, 35],
       [45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]])

## Numpy Indexing and Selection


In [ ]:
#Create array below
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [ ]:
mat[1:3,1:3]


array([[ 6,  7],
       [10, 11]])

In [ ]:
mat[1:3, [1,2]]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [ ]:
mat[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [ ]:
mat[1,[0,2]]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [ ]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
mat[:,2]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [ ]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [ ]:
#mat[[[1,1,3,3]],[[0,3,0,2]]]   bakacağız yapamadık array([[ 5, 77],[13, 77]])


## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [ ]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
a=mat[mat<10]
a

array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
b=mat[mat>12]
b

array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
arr2=np.add(a,b)
arr2

array([78, 79, 81, 18, 20, 85, 25])

In [ ]:
a+b

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [ ]:
np.std(arr2)

29.700546274093877

#### 22. Get the sum of second column from array above

In [ ]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
np.sum(mat[:,1])

32

#### 23. Get the median,mean and std of 3rd row from array above

In [ ]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
mat[:,2]=[3,7,11,15]
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
#median
np.median(mat[2])

10.5

In [ ]:
#mean
np.mean(mat[2])

10.5

In [ ]:
#std
np.std(mat[2])

1.118033988749895

# Pandas Section

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [ ]:
sal=pd.read_csv('/content/drive/MyDrive/Salaries.csv')

In [ ]:
sal.head(5)
#sal.iloc[:5]

0  ...                                             4
Id                                                             1  ...                                             5
EmployeeName                                      NATHANIEL FORD  ...                               PATRICK GARDNER
JobTitle          GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  ...  DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
BasePay                                                   167411  ...                                        134402
OvertimePay                                                    0  ...                                          9737
OtherPay                                                  400184  ...                                        182235
Benefits                                                     NaN  ...                                           NaN
TotalPay                                                  567595  ...                                        326373
TotalPayBenefits                                          567595  ...                                        326373
Year                                                        2011  ...                                          2011
Notes                                                        NaN  ...                                           NaN
Agency                                             San Francisco  ...                                 San Francisco
Status                                                       NaN  ...                                           NaN

[13 rows x 5 columns]

In [ ]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [ ]:
sal.describe().T

count          mean  ...         75%        max
Id                148654.0  74327.500000  ...  111490.750  148654.00
BasePay           148045.0  66325.448841  ...   94691.050  319275.01
OvertimePay       148650.0   5066.059886  ...    4658.175  245131.88
OtherPay          148650.0   3648.767297  ...    4236.065  400184.25
Benefits          112491.0  25007.893151  ...   35566.855   96570.66
TotalPay          148654.0  74768.321972  ...  105839.135  567595.43
TotalPayBenefits  148654.0  93692.554811  ...  132876.450  567595.43
Year              148654.0   2012.522643  ...    2014.000    2014.00
Notes                  0.0           NaN  ...         NaN        NaN
Status                 0.0           NaN  ...         NaN        NaN

[10 rows x 8 columns]

**How many different year value are there**

In [ ]:
sal.Year.value_counts()   #sal["Year"].value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [ ]:
#max
max(sal.TotalPay)

567595.43

In [ ]:
#avg
sal_avg=sal["TotalPay"].mean()
sal_avg

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [ ]:
(sal.TotalPay>sal_avg).value_counts() 

False    79165
True     69489
Name: TotalPay, dtype: int64

In [ ]:
aaaa= sal[sal.TotalPay>sal_avg].TotalPay
aaaa.count()

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [ ]:
sal["TotalPayBenefits"][2]  #İSTEDİĞİMİZ SÜTÜNDAKİ istediğimiz satır

335279.91

In [ ]:
sal[sal["EmployeeName"]=="ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

In [ ]:
#sal[sal["EmployeeName"]=="ALBERT PARDINI"]

Id    EmployeeName  ...         Agency  Status
2   3  ALBERT PARDINI  ...  San Francisco     NaN

[1 rows x 13 columns]

In [ ]:
"ALBERT PARDINI" in sal["EmployeeName"] 

False

**Who is lowest paid person**

In [ ]:
sal["EmployeeName"][sal["TotalPay"]== min(sal["TotalPay"])]

148653    Joe Lopez
Name: EmployeeName, dtype: object

In [ ]:
min(sal["TotalPay"])

-618.13

In [ ]:
[sal.TotalPay.sort_values(ascending=False).tail(1)] 

[148653   -618.13
 Name: TotalPay, dtype: float64]

In [ ]:
sal.TotalPay.sort_values().head(1)

148653   -618.13
Name: TotalPay, dtype: float64

**What are the unique Jobs in dataset?**

In [ ]:
sal.JobTitle.nunique()

2159

In [ ]:
sal["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [ ]:
sal.JobTitle.value_counts()

Transit Operator                             7036
Special Nurse                                4389
Registered Nurse                             3736
Public Svc Aide-Public Works                 2518
Police Officer 3                             2421
                                             ... 
AIRPORT MECHANICAL MAINTENANCE SUPERVISOR       1
ASSISTANT DIRECTOR OF CLINICAL SERVICES I       1
POWER HOUSE ELECTRICIAN SUPERVISOR I            1
ATTORNEY FOR THE PUBLIC ADMINISTRATOR           1
SENIOR GENERAL UTILITY MECHANIC                 1
Name: JobTitle, Length: 2159, dtype: int64

In [ ]:
sal.JobTitle.value_counts(ascending=True).head(3)

SENIOR GENERAL UTILITY MECHANIC          1
ATTORNEY FOR THE PUBLIC ADMINISTRATOR    1
POWER HOUSE ELECTRICIAN SUPERVISOR I     1
Name: JobTitle, dtype: int64

In [ ]:
sal.JobTitle.value_counts().tail(3)

POWER HOUSE ELECTRICIAN SUPERVISOR I     1
ATTORNEY FOR THE PUBLIC ADMINISTRATOR    1
SENIOR GENERAL UTILITY MECHANIC          1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [ ]:
len(sal[sal["TotalPayBenefits"]>sal["TotalPayBenefits"].mean()].loc[sal['Year'] == 2012])


20366

In [ ]:
sal[(sal["Year"]==2012)&(sal["TotalPayBenefits"]>sal["TotalPayBenefits"].mean())]["Id"].count()

20366

In [ ]:
sal["TotalPayBenefits"].mean()

93692.55481056834

**How many people have the word Manager in their job title?**

In [ ]:
#use apply function here


In [ ]:
#use apply function here                                   Kaç kişinin iş unvanında Yönetici kelimesi var?
def chief_string(title):
    if 'manager' in title.lower():
        return True
    else:
        return False

sum(sal['JobTitle'].apply(chief_string))

4110

In [ ]:
#sum(map(chief_string,sal['JobTitle']))  map sadece serilerde apply dataframelarda kullanılır.

4110

In [ ]:
sal[sal["JobTitle"]=="Mobile Equipment Supervisor"]

Id   EmployeeName  ...         Agency  Status
57495  57496  Michael Handy  ...  San Francisco     NaN

[1 rows x 13 columns]

In [ ]:
sal[sal["JobTitle"]=="GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY"]

Id    EmployeeName  ...         Agency  Status
0    1  NATHANIEL FORD  ...  San Francisco     NaN
83  84  EDWARD REISKIN  ...  San Francisco     NaN

[2 rows x 13 columns]

In [ ]:
sal[ LIKE"MANAGER"]

SyntaxError: ignored

In [ ]:
sal.filter(lambda x: for x["JobTitle"] in "MANAGER" x.count())


SyntaxError: ignored

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [ ]:
sal.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [ ]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [ ]:
sal_new=sal.iloc[:,[1,2,7,8]]                  # sonra iloc olduğu için indeksleri çağırıyoruz.indexlere bakmak için infoyu kullan
sal_new

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 4 columns]

In [ ]:
sal_new=sal.drop(["BasePay","OvertimePay","OtherPay","Benefits","Year",	"Notes",	"Agency",	"Status"], axis=1)
#sal.drop(columns = ["BasePay","OvertimePay","OtherPay","Benefits","Year",	"Notes",	"Agency",	"Status"])
sal_new

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0            1     NATHANIEL FORD  ...  567595.43         567595.43
1            2       GARY JIMENEZ  ...  538909.28         538909.28
2            3     ALBERT PARDINI  ...  335279.91         335279.91
3            4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4            5    PATRICK GARDNER  ...  326373.19         326373.19
...        ...                ...  ...        ...               ...
148649  148650      Roy I Tillery  ...       0.00              0.00
148650  148651       Not provided  ...       0.00              0.00
148651  148652       Not provided  ...       0.00              0.00
148652  148653       Not provided  ...       0.00              0.00
148653  148654          Joe Lopez  ...    -618.13           -618.13

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [ ]:
sal_new=sal.iloc[:,1:9]
sal_new

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 8 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [ ]:
sal_new.describe()

TotalPay  TotalPayBenefits
count  148654.000000     148654.000000
mean    74768.321972      93692.554811
std     50517.005274      62793.533483
min      -618.130000       -618.130000
25%     36168.995000      44065.650000
50%     71426.610000      92404.090000
75%    105839.135000     132876.450000
max    567595.430000     567595.430000

In [ ]:
sal[(sal.TotalPayBenefits > sal.TotalPayBenefits.min()) & (sal.TotalPayBenefits < sal.TotalPayBenefits.mean())]["EmployeeName"]    # ikinci sorgu şekli kullanılarak çoklu sorgunun yapılması

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object

In [ ]:
sal[(sal["TotalPayBenefits"]>sal["TotalPayBenefits"].min()) & (sal["TotalPayBenefits"]<sal["TotalPayBenefits"].mean())][["EmployeeName"]]

EmployeeName
10806          KWE LEE
10807   MIGUEL CARO JR
10808    JOANNE MORRIS
10809    LAYLA WELBORN
10810          LE BANH
...                ...
148648     Leon Walker
148649   Roy I Tillery
148650    Not provided
148651    Not provided
148652    Not provided

[75649 rows x 1 columns]

In [ ]:
sal_new[(sal_new["TotalPay"]>-618.13)&(sal_new["TotalPay"]<74768.32)]

EmployeeName  ... TotalPayBenefits
15847   TATYANA ROTENBERG  ...         74764.87
15848         WINSTON HOM  ...         74761.55
15849        CRAIG RIGLER  ...         74759.92
15850           WENDY TAN  ...         74756.76
15851      KENNETH BREWER  ...         74751.59
...                   ...  ...              ...
148648        Leon Walker  ...             0.00
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00

[79164 rows x 4 columns]