<a href="https://colab.research.google.com/github/glcn35/PANDAS/blob/main/DAwPy_S3_(Pandas_Series)_empty.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 3</p><h1>

# Pandas Series

In [1]:
import numpy as np
import pandas as pd

## Creating a Pandas Series

pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)

One-dimensional ndarray with axis labels (including time series).

In [2]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

### **Using Lists**

In [3]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series([10, 20, 30])

0    10
1    20
2    30
dtype: int64

### **Using NumPy Arrays**

In [6]:
arr

array([10, 20, 30])

In [8]:
pd.Series(data=arr, index=labels)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(data=arr, index=(3,4,5))

3    10
4    20
5    30
dtype: int64

### **Using Dictionary**

In [11]:
d

{'a': 10, 'b': 20, 'c': 30}

In [12]:
pd.Series(d)        #dict key valueları alıp satır sütün yaptı

a    10
b    20
c    30
dtype: int64

In [13]:
pd.Series(d ,index=["q","c","y"])   #sadece dict te eşleşen indexi döndürür.diğerleirni nan plarak gösterir.içerde nan gördüğü için 30.0 floata çevirdi. nanın default değeri floattır.

q     NaN
c    30.0
y     NaN
dtype: float64

In [14]:
type(np.nan)

float

### Using Scalar Value

In [15]:
pd.Series(data="gülcan")

0    gülcan
dtype: object

In [16]:
pd.Series(data="gülcan", index=range(1,5)) 

1    gülcan
2    gülcan
3    gülcan
4    gülcan
dtype: object

### Data in a Series

A pandas Series can hold a variety of object types:

{} or set()

In [18]:
set1= {1,2,3,6}   #setler sıları olamadığı için indexlenemiyor.

In [19]:
pd.Series(set1)

TypeError: ignored

In [21]:
set2=set([1,2,3,4])

In [22]:
pd.Series(set2)

TypeError: ignored

In [23]:
pd.Series([set,list,dict])

0     <class 'set'>
1    <class 'list'>
2    <class 'dict'>
dtype: object

In [25]:
pd.Series([set,list,dict])[0]([2,3,4,5,67,3])  #set unique döndürür 3 ten 1 tane

{2, 3, 4, 5, 67}

In [39]:
pd.Series([set,list,dict])[2]({"ali":2,"veli":3})

{'ali': 2, 'veli': 3}

In [43]:
pd.Series([set, list, dict])[2]([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'guido': 4127, 'jack': 4098, 'sape': 4139}

In [26]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [27]:
pd.Series([sum,print,len])[0]([3,5,7])

15

In [28]:
mix_data = ['Aziz', 2, True]

In [30]:
ser= pd.Series(mix_data)
ser

0    Aziz
1       2
2    True
dtype: object

In [33]:
ser.dtype                   #'o' object

dtype('O')

In [34]:
type(ser)

pandas.core.series.Series

In [35]:
type(ser[2])    #tipleri muhafaza eder

bool

In [36]:
arr= np.array(mix_data)
arr

array(['Aziz', '2', 'True'], dtype='<U4')

In [37]:
type(arr[1])

numpy.str_

In [38]:
type(arr[2])  #bütün hepsini tipini aynı yapar numpy. aradaki önemli fark

numpy.str_

### Basic Attributes of Series

In [42]:
ser= pd.Series(np.random.randint(0,100,7))
ser

0    56
1    80
2    24
3    94
4    59
5    57
6    31
dtype: int64

In [44]:
ser.dtype

dtype('int64')

In [45]:
type(ser)

pandas.core.series.Series

In [46]:
ser.shape

(7,)

In [47]:
ser.size

7

In [49]:
len(ser)

7

In [48]:
ser.ndim

1

In [56]:
s= pd.Series([np.nan,3,6,"ali"])
s

0    NaN
1      3
2      6
3    ali
dtype: object

In [54]:
s.size   #nanlarıda sayar

4

In [57]:
ser.index

RangeIndex(start=0, stop=7, step=1)

In [58]:
list(ser.index)

[0, 1, 2, 3, 4, 5, 6]

In [59]:
for i in ser.index:
  print(i)

0
1
2
3
4
5
6


In [64]:
ser.keys

<bound method Series.keys of 0    56
1    80
2    24
3    94
4    59
5    57
6    31
dtype: int64>

In [63]:
ser.values

array([56, 80, 24, 94, 59, 57, 31])

In [66]:
ser.items()

In [67]:
ser.items

<bound method Series.items of 0    56
1    80
2    24
3    94
4    59
5    57
6    31
dtype: int64>

In [68]:
list(ser.items())

[(0, 56), (1, 80), (2, 24), (3, 94), (4, 59), (5, 57), (6, 31)]

In [69]:
for index,value in ser.items():
  print(f"index: {index}, value{value}")

index: 0, value56
index: 1, value80
index: 2, value24
index: 3, value94
index: 4, value59
index: 5, value57
index: 6, value31


In [74]:
ser = pd.Series(data = np.random.randint(0,25,10), index = [i for i in "cbaefdgihj"])
ser

c    12
b     6
a     3
e    14
f    22
d     6
g     1
i     8
h    10
j     1
dtype: int64

In [75]:
ser.head()

c    12
b     6
a     3
e    14
f    22
dtype: int64

In [76]:
ser.tail()

d     6
g     1
i     8
h    10
j     1
dtype: int64

In [77]:
ser.sample(3)   #random olarak kaç tane istersek o kadar satırı gösterir

j     1
d     6
f    22
dtype: int64

In [78]:
ser.sort_index(ascending=True)   #İNDEXİ ALFABETİK SIRALAYABİLDİM

a     3
b     6
c    12
d     6
e    14
f    22
g     1
h    10
i     8
j     1
dtype: int64

In [79]:
ser.sort_values()

g     1
j     1
a     3
b     6
d     6
i     8
h    10
c    12
e    14
f    22
dtype: int64

In [80]:
ser.sort_values(ascending=False)

f    22
e    14
c    12
h    10
i     8
d     6
b     6
a     3
j     1
g     1
dtype: int64

In [81]:
ser

c    12
b     6
a     3
e    14
f    22
d     6
g     1
i     8
h    10
j     1
dtype: int64

In [82]:
ser.isin([5,9])  #hangi değerlerim 5 veya 9

c    False
b    False
a    False
e    False
f    False
d    False
g    False
i    False
h    False
j    False
dtype: bool

In [83]:
ser.isin([3,8])  

c    False
b    False
a     True
e    False
f    False
d    False
g    False
i     True
h    False
j    False
dtype: bool

In [88]:
pd.Series([i for i in "CLARUSWAY"])

0    C
1    L
2    A
3    R
4    U
5    S
6    W
7    A
8    Y
dtype: object

## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [108]:
ser1=pd.Series([1,2,3,4,],index = ['USA', 'Germany','USSR', 'Japan'])
serrr = pd.Series([1,2,3,4,5],index = ['USA', 'Germany','USSR', 'Japan',"USA"])
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [96]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [91]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [92]:
ser1.sort_index()

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [98]:
ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
dtype: int64

In [99]:
ser1[1]

2

In [100]:
ser1["Germany"]

2

In [109]:
serrr["USA"]

USA    1
USA    5
dtype: int64

In [105]:
ser1+ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [110]:
serrr+ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USA        6.0
USSR       NaN
dtype: float64

Operations are then also done based off of index:

In [111]:
ser3 = pd.Series(data = ["a", "b", "c", "d"])
ser3

0    a
1    b
2    c
3    d
dtype: object

In [112]:
ser3[0]

'a'

In [113]:
ser3[:2]

0    a
1    b
dtype: object

In [114]:
ser3[::-1]

3    d
2    c
1    b
0    a
dtype: object

In [116]:
ser3.sort_index(ascending=False)

3    d
2    c
1    b
0    a
dtype: object

### pandas_series[index] | pandas_series[[indices, indices...]]

In [117]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [121]:
panser["terry","orion"]]

KeyError: ignored

In [120]:
panser["terry"]

121

In [122]:
panser["terry":"orion"]   #orionu da aldı. isimlerle çağırırken ikiside dahil olur

terry      121
micheal    200
orion      150
dtype: int64

In [123]:
panser[0:3]   #sayılarla çağırıken 3 dahil edilmez

terry      121
micheal    200
orion      150
dtype: int64

### Recap for Several Selecting Attributes

In [124]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [126]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [128]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [130]:
panser.values

array([121, 200, 150,  99])

In [132]:
panser.items()

In [140]:
for index,value in panser.items():
    print(index,value)

terry 121
micheal 200
orion 150
jason 99


In [141]:
"terry" in panser

True

In [145]:
"terry" in panser.index

True

In [142]:
"bob" in panser  #indexi direkt sorgulayabiliriz. value larda aramak için extra value yazmak gerekir

False

In [143]:
200 in panser.values    

True

In [144]:
2000 in panser.values

False

In [147]:
panser.isin([200,150])

terry      False
micheal     True
orion       True
jason      False
dtype: bool

In [148]:
panser["terry"] =90   #atama yapp değiştirebiliriz.
panser

terry       90
micheal    200
orion      150
jason       99
dtype: int64

In [149]:
panser[panser>100]

micheal    200
orion      150
dtype: int64

In [150]:
panser[panser>100] = 175

In [151]:
panser

terry       90
micheal    175
orion      175
jason       99
dtype: int64